apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ./stable/base
- ./stable/cluster-install/workflow-controller-rbac
- ./stable/cluster-install/argo-server-rbac
- templates.yaml
patchesStrategicMerge:
- config.yaml
namespace: argo
